contact_links:
  - about: Ask a question or request support here
    name: Ask for Support
    url: >-
      https://github.com/ETHGreen-Network/ethgreen-blockchain/discussions/new?category=support
  - about: Request a new feature or idea here
    name: Make a Request
    url: >-
      https://github.com/ETHGreen-Network/ethgreen-blockchain/discussions/new?category=ideas
  - about: Get support on the ethgreen Keybase chat channels.
    name: Join the Keybase.io support chat
    url: 'https://keybase.io/team/ethgreen_network.public'
